FROM fedora:44

RUN dnf -y update && dnf -y install \
    podman \
    dialog \
    findutils \
    util-linux \
    gdisk \
    ncurses \
    curl \
    git \
    && dnf clean all

COPY install.sh /usr/local/bin/fruitadens-install
RUN chmod +x /usr/local/bin/fruitadens-install

ENTRYPOINT ["/usr/local/bin/fruitadens-install"]
