set shell := ["bash", "-c"]

IMAGE_NAME := "fruitadens-installer"
INSTALLER_DIR := "installer"

build:
	podman build -t $(IMAGE_NAME):latest $(INSTALLER_DIR)

push:
	podman push $(IMAGE_NAME):latest

clean:
	rm -rf installer/build
